[ui.anchors]
bottom = true
left = true
right = true
top = true

[ui.window]
h_align = "fill"
v_align = "fill"

[ui.window.box]
h_align = "center"
width = 450
[ui.window.box.margins]
top = 200

[ui.window.box.bar]
orientation = "horizontal"
position = "end"
[ui.window.box.bar.entry]
h_align = "fill"
h_expand = true
[ui.window.box.bar.entry.icon]
h_align = "center"
h_expand = true
pixel_size = 24
theme = ""

[ui.window.box.scroll]
h_scrollbar_policy = "external"
v_scrollbar_policy = "never"

[ui.window.box.scroll.list]
marker_color = "#1BFFE1"
always_show = false
min_height = 0
max_height = 400
max_width = 0
min_width = 0
[ui.window.box.scroll.list.margins]
top = 26

[ui.window.box.scroll.list.item.icon]
pixel_size = 26
theme = ""
[ui.window.box.scroll.list.item.icon.margins]
end = 10

[ui.window.box.scroll.list.item.text.sub]
hide = true

[ui.window.box.search.input]
h_align = "fill"
h_expand = true

[ui.window.box.search.prompt]
hide = true
[ui.window.box.search.clear]
hide = true
[ui.window.box.search.spinner]
hide = true
